-- DUBU v4 migration
-- Run this AFTER the original DUBU supabase_setup.sql.
-- Keeps existing bookings and adds the new 5-page data model.

create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  phone text,
  note text,
  created_at timestamptz not null default now()
);

create table if not exists public.services (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  price numeric not null default 300,
  duration integer not null default 60,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.bookings add column if not exists customer_id bigint references public.customers(id) on delete set null;
alter table public.bookings add column if not exists service_id bigint references public.services(id) on delete set null;
alter table public.bookings add column if not exists service_name text;
alter table public.bookings add column if not exists price numeric not null default 300;
alter table public.bookings add column if not exists status text not null default 'waiting';
alter table public.bookings add column if not exists payment_status text not null default 'unpaid';

alter table public.customers enable row level security;
alter table public.services enable row level security;

drop policy if exists "dubu customers select" on public.customers;
drop policy if exists "dubu customers insert" on public.customers;
drop policy if exists "dubu customers update" on public.customers;
drop policy if exists "dubu customers delete" on public.customers;
create policy "dubu customers select" on public.customers for select to authenticated using (auth.uid()=user_id);
create policy "dubu customers insert" on public.customers for insert to authenticated with check (auth.uid()=user_id);
create policy "dubu customers update" on public.customers for update to authenticated using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy "dubu customers delete" on public.customers for delete to authenticated using (auth.uid()=user_id);

drop policy if exists "dubu services select" on public.services;
drop policy if exists "dubu services insert" on public.services;
drop policy if exists "dubu services update" on public.services;
drop policy if exists "dubu services delete" on public.services;
create policy "dubu services select" on public.services for select to authenticated using (auth.uid()=user_id);
create policy "dubu services insert" on public.services for insert to authenticated with check (auth.uid()=user_id);
create policy "dubu services update" on public.services for update to authenticated using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy "dubu services delete" on public.services for delete to authenticated using (auth.uid()=user_id);

-- Make booking access user-scoped (safe for a shared account).
drop policy if exists "authenticated can read bookings" on public.bookings;
drop policy if exists "authenticated can update bookings" on public.bookings;
drop policy if exists "authenticated can delete bookings" on public.bookings;
create policy "dubu bookings select" on public.bookings for select to authenticated using (auth.uid()=user_id);
create policy "dubu bookings update" on public.bookings for update to authenticated using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy "dubu bookings delete" on public.bookings for delete to authenticated using (auth.uid()=user_id);

-- Seed one default service per existing user.
insert into public.services(user_id,name,price,duration)
select id,'ดูดวงทั่วไป',300,60 from auth.users u
where not exists (select 1 from public.services s where s.user_id=u.id);

-- Backfill customer records from existing bookings.
insert into public.customers(user_id,name,phone)
select distinct b.user_id,b.customer_name,b.phone
from public.bookings b
where not exists (
  select 1 from public.customers c
  where c.user_id=b.user_id and c.name=b.customer_name
);

update public.bookings b
set customer_id=c.id
from public.customers c
where b.customer_id is null and c.user_id=b.user_id and c.name=b.customer_name;

update public.bookings b
set service_name=coalesce(service_name,'ดูดวงทั่วไป')
where service_name is null;

-- Enforce no duplicate active time slot per date.
create unique index if not exists dubu_booking_date_time_unique
on public.bookings(date,time)
where status <> 'cancelled';
